### ISSUE TITLE
Loading deep renders in Nuke as deepread

### ISSUE THREAD

**Issue by krishnaavril** [ynput/ayon-nuke#22]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

Nuke is loading the deep rendered exr's from houdini karma published renders as a general read node through ayon loader

### Expected Behavior:

Nuke should load the general exrs as a read node
Nuke should load the deep exrs as a deepread node

### Version

1.0.0

### What platform you are running on?

Windows

### Steps To Reproduce:

Publish any deep render and general exr in ayon from houdini karma
try to load the deep exr and general exr through the ayon loader in nuke

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

**Comment by krishnaavril** [comment]
https://drive.google.com/drive/folders/1a_cMSgq_Fa8Chjq-NwU_7xTyqNGnjnIo?usp=sharing

I've added an exr in the above link to the test. generally, nuke is smart in that it loads the deep exr as a deep node when you drag and drop in the node graph, you can try with the above-sent exrs

```Easiest would be to add a separate Load Deep option in loader, but might be poluting things```
![image](https://github.com/user-attachments/assets/42888a6e-04dd-4055-9e04-c4d389451278)
I think so, I found one option but that default loads all the exr's as deep read. which is not a good idea. If we have another option when loading it is the best, other than something Nuke detects by file name or something!

I vote for your 2nd point if its possible technically

```Would you like to ever load a deep exr into a regular read node?```
Its not a ideal way of working, they both are lot different and it confuses artists too

**Comment by jakubjezek001** [comment]
@krishnaavril, have you tried using the Load Clip option box and enabled `Read with deep exr` for loading? Did that fail, or is Houdini Karma deep exr somehow specific, causing this process to fail?

**Comment by BigRoy** [comment]
Is that sufficient for productions? :) If so, feel free to close or let us know what's still needed.
