### ISSUE TITLE
Adding `AYON_LOG_NO_COLORS ` into prelaunch hooks

### ISSUE THREAD

**Issue by jakubjezek001** [ynput/ayon-nuke#24]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Please describe the feature you have in mind and explain what the current shortcomings are?

Nuke on Windows prints the Ayon logs in the console, but the logs appear colored. The console doesn't interpret the control sequences correctly, making the logs unreadable.

### How would you imagine the implementation of the feature?

Adding `AYON_LOG_NO_COLORS` into default environment via prelaunch hook

```
{
    "AYON_LOG_NO_COLORS": "1"
}
```
![image](https://github.com/user-attachments/assets/7647347e-0c08-497e-a47c-2292c0fb30ad)

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the enhancement request.

**Comment by jakubjezek001** [comment]
So it seems like `AYON_LOG_NO_COLORS` environment is not having any support in ayon-core. Or is ther other place to look at? @antirotor or @iLLiCiTiT ?

**Comment by iLLiCiTiT** [comment]
If it is must have, then nuke addon can set it in `add_implementation_envs` on `NukeAddon`.

> So it seems like AYON_LOG_NO_COLORS environment is not having any support in ayon-core. Or is ther other place to look at?

It is handled here https://github.com/ynput/ayon-core/blob/develop/client/ayon_core/lib/terminal.py#L42
