### ISSUE TITLE
AYON 'onScriptSave' callback can block saving workfile if it errors

### ISSUE THREAD

**Issue by jrsndl** [ynput/ayon-nuke#33]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

Ayon uses onScriptSave callback to update nodes' colors. If this fails by any reason, artist is not able to save the file.

https://github.com/ynput/ayon-nuke/blob/b92271160f3547f986e0b9425275ef7f11b2bbdf/client/ayon_nuke/api/pipeline.py#L166

### Expected Behavior:

Failing the callback should not block the save.

### Version

1.0.0

### What platform you are running on?

Windows

### Steps To Reproduce:

1. Open Nuke workfile, make some changes
2. Stop Ayon server
3. Save

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

**Comment by BigRoy** [comment]
Thanks for the report.

1. Do you have a reproducable how to make it fail? 
    - And does it still log an error / provide a stack trace? If so, could you attach one?
2. Does it work if we make the callback itself run completely within a `try..except`

**Comment by jrsndl** [comment]
> 1. Do you have a reproducable how to make it fail?

This did happen when artist lost connection to the Ayon server, I will have to find a way to sabotage it.

>    * And does it still log an error / provide a stack trace? If so, could you attach one?

Yes. I didn't save the trace, but it failed here:
[    filtered_containers = filter_containers(containers, project_name)
](https://github.com/ynput/ayon-nuke/blob/b92271160f3547f986e0b9425275ef7f11b2bbdf/client/ayon_nuke/api/lib.py#L822)

> 2. Does it work if we make the callback itself run completely within a `try..except`

Yes, try / except in check_inventory_versions worked.

Sorry fon non-complete report, I had to help artists yesterday, making issue today so I do not forget.

BTW I had the same problem in OpenPype, once in a while the OpenPype data in Nuke node get corrupted, and artist was not able to save.
