### ISSUE TITLE
Nuke: deep image exr loading

### ISSUE THREAD

**Issue by jakubjezek001** [ynput/ayon-nuke#6]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Please describe the feature you have in mind and explain what the current shortcomings are?

Deep image ex can occasionally be used in productions and we do not support loading them yet.

### How would you imagine the implementation of the feature?

enhancing actual LoadClip plugin
find some way how to identify exr in representation as deep images - OIIO can read metadata and flag it during publishing into version and save it into representation.data. So during loading this flag will tell the plugin to chose different Read node.
if deep image representation is identified then use DeepRead node.
rest is the same as normal Read node.

[cuID:[OP-4468](https://app.clickup.com/t/33a7ey2)]

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the enhancement request.

### Describe alternatives you've considered:

asdas

**Comment by mkolar** [comment]
I'd say, let's not waste time on this, until someone actually requests and fund it. I haven't heard a mention  of deep for years.
