### ISSUE TITLE
Create Write Node: Do not format full anatomy

### ISSUE THREAD

**Issue by BigRoy** [ynput/ayon-nuke#9]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Please describe the feature you have in mind and explain what the current shortcomings are?

Currently when creating a write node via the publisher UI it will format the file path using `anatomy.format()` which formats all templates instead of the only template we actually end up needing.

See [code](https://github.com/ynput/ayon-nuke/blob/a2aefa035e7bf57027dcd8061652323ad3be29a8/client/ayon_nuke/api/lib.py#L959-L996).

This has performance implications, but also has the downside that if any of the OTHER templates errors using the data we're providing it the user can't create a write node - even though it didn't need that data at all.

### How would you imagine the implementation of the feature?

Use the relevant template instead and `template.format_strict(data)` with that instead.

For example see [logic here](https://github.com/ynput/ayon-core/blob/43713d7ac01f021ff8a81a59e87c7acc5142037c/client/ayon_core/tools/workfiles/models/workfiles.py#L303-L307)

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the enhancement request.

### Describe alternatives you've considered:

There's also a note that `anatomy.format()` shouldn't directly error on a template that it can't format, but instead should do so only when that template starts getting accessed/used later.

### Additional context:

[See Ynput discord discussion](https://discord.com/channels/517362899170230292/563751989075378201/1266353908507213934)

**Comment by mkolar** [comment]
resolved
